name: release

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python 3.12
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.12

      - name: Install system deps
        shell: bash
        run: |
          pip install uv

      - name: Build package
        run: |
          uv build

      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4

      - name: Publish package on TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/
